POST http://localhost:3333/videos
Content-Type: application/json

{
    "title": "video python",
    "description": "descrição python",
    "duration": 200
}


###

GET http://localhost:3333/videos?search=python


###

PUT http://localhost:3333/videos/0835ee36-591e-493b-a8e6-aef87c73d30b
Content-Type: application/json

{
    "title": "video 1",
    "description": "esse é o video 01",
    "duration": 300
}

###
DELETE http://localhost:3333/videos/0835ee36-591e-493b-a8e6-aef87c73d30b
